### ISSUE TITLE
all the calls to Backbone.history.navigate use the `replace` option

### ISSUE THREAD

**Issue by moloko** [cgkineo/adapt-quicknav#14]
This will 'update the URL without creating an entry in the browser's history'

Pretty sure this is not a good thing if the course is using a 'back' button in the navbar - since it will then stop that from working properly...?

**Comment by joe-replin** [comment]
Went to add something similar here. Good to know this has already been noticed. With quicknav enabled, users might be inspired to click through a few content pages through the quicknav buttons. The navigation bar's back button in this case will take you back to the previous page (and inside of a continuous page loop between two pages). If the quicknav buttons are set to absolute paths and not to the next page, the navigation bar's back button just takes you up through the menu structure. It appears though quicknav is failing to record the history correctly which is due to:

adapt-quicknav.js – line 125
Backbone.history.navigate("#/id/" + pages[indexOfPage], {trigger: true, **replace: true**});

**Comment by oliverfoster** [comment]
Ya. Rediscovered this again today. I concur.
