### ISSUE TITLE
Use of Tooltips in Edge causes jumping/shifting

### ISSUE THREAD

**Issue by chucklorenz** [cgkineo/adapt-quicknav#54]
Added quickNav component. Configured it for previous, home, and next with icons. Enabled Tooltips ("_showTooltip": true).

When hovering over quickNav icon in Edge, a momentary shifting of elements is seen. On closer inspection, it appears to involve the inline style "top: 0px". In F12 devtools, uncheck "top: 0px" on the tooltip div and you'll see a secondary vertical scrollbar comes into view. Seems that the transition from "visibility: hidden" to "visibility: visible" is exposing the transition from "top: auto" to "top: 0px" and invoking a scrollbar during that period. 

I was able to eliminate this behaviour by switching the rules from "visibility: hidden" to "display: none". Perhaps this has impact on some possible CSS transitions, but not for my current project. 

framework 3.0
quicknav 3.0.5
edge 41.16299
Windows 10 Pro

**Comment by joe-replin** [comment]
Had a similar issue with high-resolution monitors.....particularly IE in a 4K screen. Quicknav is only be toggling visibility so positioning, I'm assuming, is being thrown off when resizing and zooming your browser. By switching to 'display' instead of 'visibility' in the tooltip.less file, the tooltip might be getting recalculated. Will keep an eye on this to see if it causes any ill effects.

Thank you @chucklorenz!

**Comment by oliverfoster** [comment]
@guywillis is this related to https://github.com/cgkineo/adapt-quicknav/blob/master/less/tooltip.less#L3 ?

**Comment by guywillis** [comment]
Quite possibly, but Chuck mentions a vertical scroll bar whereas the CSS linked to above relates to a fix for a horizontal scroll bar that appears on tooltip hover in IE11.

**Comment by oliverfoster** [comment]
![image](https://user-images.githubusercontent.com/7974663/64518304-d38da880-d2e9-11e9-948c-0621f66c4bfc.png)

![image](https://user-images.githubusercontent.com/7974663/64518344-e43e1e80-d2e9-11e9-9a5d-e69ae896d837.png)

Cannot replicate in latest version.
